name: battery_model
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3
    - matplotlib
    - numpy
    - pandas
    - jupyterlab
    - seaborn
    - nb_conda_kernels
    - altair
    - pyomo
    - glpk